### ISSUE TITLE
pip install pyspin exits with an error

### ISSUE THREAD

**Issue by DrBwts** [lord63/py-spin#21]
Win 10 x64, Python 3.10, pip setup-tools 67.6.1

As Admin I have tried both on-line & off line installs, both give the same errors. 
Full traceback,

```
>pip install pyspin
Collecting pyspin
  Using cached pyspin-1.1.1-py2.py3-none-any.whl (5.3 kB)
Collecting futures
  Using cached futures-3.0.5.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Users\sengnr3\.conda\envs\uEye\lib\site-packages\setuptools\__init__.py", line 268, in <module>
          monkey.patch_all()
        File "C:\Users\sengnr3\.conda\envs\uEye\lib\site-packages\setuptools\monkey.py", line 97, in patch_all
          patch_for_msvc_specialized_compiler()
        File "C:\Users\sengnr3\.conda\envs\uEye\lib\site-packages\setuptools\monkey.py", line 157, in patch_for_msvc_specialized_compiler
          patch_func(*msvc14('_get_vc_env'))
        File "C:\Users\sengnr3\.conda\envs\uEye\lib\site-packages\setuptools\monkey.py", line 147, in patch_params
          mod = import_module(mod_name)
        File "C:\Users\sengnr3\.conda\envs\uEye\lib\importlib\__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "C:\Users\sengnr3\.conda\envs\uEye\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 20, in <module>
          import unittest.mock as mock
        File "C:\Users\sengnr3\.conda\envs\uEye\lib\unittest\mock.py", line 26, in <module>
          import asyncio
        File "C:\Users\sengnr3\.conda\envs\uEye\lib\asyncio\__init__.py", line 8, in <module>
          from .base_events import *
        File "C:\Users\sengnr3\.conda\envs\uEye\lib\asyncio\base_events.py", line 18, in <module>
          import concurrent.futures
        File "C:\Users\sengnr3\AppData\Local\Temp\pip-install-4fup4a9q\futures_2c256a20a5e845f6b8dcbef67c2a0be9\concurrent\futures\__init__.py", line 8, in <module>
          from concurrent.futures._base import (FIRST_COMPLETED,
        File "C:\Users\sengnr3\AppData\Local\Temp\pip-install-4fup4a9q\futures_2c256a20a5e845f6b8dcbef67c2a0be9\concurrent\futures\_base.py", line 357
          raise type(self._exception), self._exception, self._traceback
                                     ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by lord63** [comment]
Hey, released a new version 1.2.0, have a try.
Let me know if still exists some problems.
